/**
 * india-geo.ts - GENERATED canonical India State -> District reference for
 * Connect location targeting + capture. DO NOT HAND-EDIT.
 *
 * Regenerate: backend `node scripts/india-geo/build-india-geo.mjs` (writes this
 * file in BOTH repos identically). Source + refresh instructions live there.
 *
 * Coverage: 35 states/UTs, 722 districts (~2018 community
 * snapshot: pre Ladakh-split / pre DNH+DD merge). Gujarat (live market) = 33.
 * Refresh from the official LGD directory when broader coverage is needed.
 *
 * Keyed by SLUG (lowercased, ascii). The web sends a slug; the backend matches
 * targeting on the same slug. This file MUST stay identical in both repos - a
 * vitest in each guards counts + unique slugs.
 */

export interface GeoDistrict {
  readonly slug: string;
  readonly name: string;
}

export interface GeoState {
  readonly slug: string;
  readonly name: string;
  readonly isUT: boolean;
  readonly districts: readonly GeoDistrict[];
}

export const INDIA_GEO: readonly GeoState[] = [
  {
    slug: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    isUT: false,
    districts: [
      { slug: 'anantapur', name: 'Anantapur' },
      { slug: 'chittoor', name: 'Chittoor' },
      { slug: 'east-godavari', name: 'East Godavari' },
      { slug: 'guntur', name: 'Guntur' },
      { slug: 'krishna', name: 'Krishna' },
      { slug: 'kurnool', name: 'Kurnool' },
      { slug: 'nellore', name: 'Nellore' },
      { slug: 'prakasam', name: 'Prakasam' },
      { slug: 'srikakulam', name: 'Srikakulam' },
      { slug: 'visakhapatnam', name: 'Visakhapatnam' },
      { slug: 'vizianagaram', name: 'Vizianagaram' },
      { slug: 'west-godavari', name: 'West Godavari' },
      { slug: 'ysr-kadapa', name: 'YSR Kadapa' },
    ],
  },
  {
    slug: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    isUT: false,
    districts: [
      { slug: 'anjaw', name: 'Anjaw' },
      { slug: 'changlang', name: 'Changlang' },
      { slug: 'dibang-valley', name: 'Dibang Valley' },
      { slug: 'east-kameng', name: 'East Kameng' },
      { slug: 'east-siang', name: 'East Siang' },
      { slug: 'kra-daadi', name: 'Kra Daadi' },
      { slug: 'kurung-kumey', name: 'Kurung Kumey' },
      { slug: 'lohit', name: 'Lohit' },
      { slug: 'longding', name: 'Longding' },
      { slug: 'lower-dibang-valley', name: 'Lower Dibang Valley' },
      { slug: 'lower-siang', name: 'Lower Siang' },
      { slug: 'lower-subansiri', name: 'Lower Subansiri' },
      { slug: 'namsai', name: 'Namsai' },
      { slug: 'papum-pare', name: 'Papum Pare' },
      { slug: 'siang', name: 'Siang' },
      { slug: 'tawang', name: 'Tawang' },
      { slug: 'tirap', name: 'Tirap' },
      { slug: 'upper-siang', name: 'Upper Siang' },
      { slug: 'upper-subansiri', name: 'Upper Subansiri' },
      { slug: 'west-kameng', name: 'West Kameng' },
      { slug: 'west-siang', name: 'West Siang' },
    ],
  },
  {
    slug: 'assam',
    name: 'Assam',
    isUT: false,
    districts: [
      { slug: 'baksa', name: 'Baksa' },
      { slug: 'barpeta', name: 'Barpeta' },
      { slug: 'biswanath', name: 'Biswanath' },
      { slug: 'bongaigaon', name: 'Bongaigaon' },
      { slug: 'cachar', name: 'Cachar' },
      { slug: 'charaideo', name: 'Charaideo' },
      { slug: 'chirang', name: 'Chirang' },
      { slug: 'darrang', name: 'Darrang' },
      { slug: 'dhemaji', name: 'Dhemaji' },
      { slug: 'dhubri', name: 'Dhubri' },
      { slug: 'dibrugarh', name: 'Dibrugarh' },
      { slug: 'dima-hasao', name: 'Dima Hasao' },
      { slug: 'goalpara', name: 'Goalpara' },
      { slug: 'golaghat', name: 'Golaghat' },
      { slug: 'hailakandi', name: 'Hailakandi' },
      { slug: 'hojai', name: 'Hojai' },
      { slug: 'jorhat', name: 'Jorhat' },
      { slug: 'kamrup', name: 'Kamrup' },
      { slug: 'kamrup-metropolitan', name: 'Kamrup Metropolitan' },
      { slug: 'karbi-anglong', name: 'Karbi Anglong' },
      { slug: 'karimganj', name: 'Karimganj' },
      { slug: 'kokrajhar', name: 'Kokrajhar' },
      { slug: 'lakhimpur', name: 'Lakhimpur' },
      { slug: 'majuli', name: 'Majuli' },
      { slug: 'morigaon', name: 'Morigaon' },
      { slug: 'nagaon', name: 'Nagaon' },
      { slug: 'nalbari', name: 'Nalbari' },
      { slug: 'sivasagar', name: 'Sivasagar' },
      { slug: 'sonitpur', name: 'Sonitpur' },
      { slug: 'south-salmara-mankachar', name: 'South Salmara-Mankachar' },
      { slug: 'tinsukia', name: 'Tinsukia' },
      { slug: 'udalguri', name: 'Udalguri' },
      { slug: 'west-karbi-anglong', name: 'West Karbi Anglong' },
    ],
  },
  {
    slug: 'bihar',
    name: 'Bihar',
    isUT: false,
    districts: [
      { slug: 'araria', name: 'Araria' },
      { slug: 'arwal', name: 'Arwal' },
      { slug: 'aurangabad', name: 'Aurangabad' },
      { slug: 'banka', name: 'Banka' },
      { slug: 'begusarai', name: 'Begusarai' },
      { slug: 'bhagalpur', name: 'Bhagalpur' },
      { slug: 'bhojpur', name: 'Bhojpur' },
      { slug: 'buxar', name: 'Buxar' },
      { slug: 'darbhanga', name: 'Darbhanga' },
      { slug: 'east-champaran-motihari', name: 'East Champaran (Motihari)' },
      { slug: 'gaya', name: 'Gaya' },
      { slug: 'gopalganj', name: 'Gopalganj' },
      { slug: 'jamui', name: 'Jamui' },
      { slug: 'jehanabad', name: 'Jehanabad' },
      { slug: 'kaimur-bhabua', name: 'Kaimur (Bhabua)' },
      { slug: 'katihar', name: 'Katihar' },
      { slug: 'khagaria', name: 'Khagaria' },
      { slug: 'kishanganj', name: 'Kishanganj' },
      { slug: 'lakhisarai', name: 'Lakhisarai' },
      { slug: 'madhepura', name: 'Madhepura' },
      { slug: 'madhubani', name: 'Madhubani' },
      { slug: 'munger-monghyr', name: 'Munger (Monghyr)' },
      { slug: 'muzaffarpur', name: 'Muzaffarpur' },
      { slug: 'nalanda', name: 'Nalanda' },
      { slug: 'nawada', name: 'Nawada' },
      { slug: 'patna', name: 'Patna' },
      { slug: 'purnia-purnea', name: 'Purnia (Purnea)' },
      { slug: 'rohtas', name: 'Rohtas' },
      { slug: 'saharsa', name: 'Saharsa' },
      { slug: 'samastipur', name: 'Samastipur' },
      { slug: 'saran', name: 'Saran' },
      { slug: 'sheikhpura', name: 'Sheikhpura' },
      { slug: 'sheohar', name: 'Sheohar' },
      { slug: 'sitamarhi', name: 'Sitamarhi' },
      { slug: 'siwan', name: 'Siwan' },
      { slug: 'supaul', name: 'Supaul' },
      { slug: 'vaishali', name: 'Vaishali' },
      { slug: 'west-champaran', name: 'West Champaran' },
    ],
  },
  {
    slug: 'chandigarh',
    name: 'Chandigarh',
    isUT: true,
    districts: [{ slug: 'chandigarh', name: 'Chandigarh' }],
  },
  {
    slug: 'chhattisgarh',
    name: 'Chhattisgarh',
    isUT: false,
    districts: [
      { slug: 'balod', name: 'Balod' },
      { slug: 'baloda-bazar', name: 'Baloda Bazar' },
      { slug: 'balrampur', name: 'Balrampur' },
      { slug: 'bastar', name: 'Bastar' },
      { slug: 'bemetara', name: 'Bemetara' },
      { slug: 'bijapur', name: 'Bijapur' },
      { slug: 'bilaspur', name: 'Bilaspur' },
      { slug: 'dantewada-south-bastar', name: 'Dantewada (South Bastar)' },
      { slug: 'dhamtari', name: 'Dhamtari' },
      { slug: 'durg', name: 'Durg' },
      { slug: 'gariyaband', name: 'Gariyaband' },
      { slug: 'janjgir-champa', name: 'Janjgir-Champa' },
      { slug: 'jashpur', name: 'Jashpur' },
      { slug: 'kabirdham-kawardha', name: 'Kabirdham (Kawardha)' },
      { slug: 'kanker-north-bastar', name: 'Kanker (North Bastar)' },
      { slug: 'kondagaon', name: 'Kondagaon' },
      { slug: 'korba', name: 'Korba' },
      { slug: 'korea-koriya', name: 'Korea (Koriya)' },
      { slug: 'mahasamund', name: 'Mahasamund' },
      { slug: 'mungeli', name: 'Mungeli' },
      { slug: 'narayanpur', name: 'Narayanpur' },
      { slug: 'raigarh', name: 'Raigarh' },
      { slug: 'raipur', name: 'Raipur' },
      { slug: 'rajnandgaon', name: 'Rajnandgaon' },
      { slug: 'sukma', name: 'Sukma' },
      { slug: 'surajpur', name: 'Surajpur' },
      { slug: 'surguja', name: 'Surguja' },
    ],
  },
  {
    slug: 'dadra-and-nagar-haveli',
    name: 'Dadra and Nagar Haveli',
    isUT: true,
    districts: [{ slug: 'dadra-nagar-haveli', name: 'Dadra & Nagar Haveli' }],
  },
  {
    slug: 'daman-and-diu',
    name: 'Daman and Diu',
    isUT: true,
    districts: [
      { slug: 'daman', name: 'Daman' },
      { slug: 'diu', name: 'Diu' },
    ],
  },
  {
    slug: 'delhi',
    name: 'Delhi',
    isUT: true,
    districts: [
      { slug: 'central-delhi', name: 'Central Delhi' },
      { slug: 'east-delhi', name: 'East Delhi' },
      { slug: 'new-delhi', name: 'New Delhi' },
      { slug: 'north-delhi', name: 'North Delhi' },
      { slug: 'north-east-delhi', name: 'North East  Delhi' },
      { slug: 'north-west-delhi', name: 'North West  Delhi' },
      { slug: 'shahdara', name: 'Shahdara' },
      { slug: 'south-delhi', name: 'South Delhi' },
      { slug: 'south-east-delhi', name: 'South East Delhi' },
      { slug: 'south-west-delhi', name: 'South West  Delhi' },
      { slug: 'west-delhi', name: 'West Delhi' },
    ],
  },
  {
    slug: 'goa',
    name: 'Goa',
    isUT: false,
    districts: [
      { slug: 'north-goa', name: 'North Goa' },
      { slug: 'south-goa', name: 'South Goa' },
    ],
  },
  {
    slug: 'gujarat',
    name: 'Gujarat',
    isUT: false,
    districts: [
      { slug: 'ahmedabad', name: 'Ahmedabad' },
      { slug: 'amreli', name: 'Amreli' },
      { slug: 'anand', name: 'Anand' },
      { slug: 'aravalli', name: 'Aravalli' },
      { slug: 'banaskantha-palanpur', name: 'Banaskantha (Palanpur)' },
      { slug: 'bharuch', name: 'Bharuch' },
      { slug: 'bhavnagar', name: 'Bhavnagar' },
      { slug: 'botad', name: 'Botad' },
      { slug: 'chhota-udepur', name: 'Chhota Udepur' },
      { slug: 'dahod', name: 'Dahod' },
      { slug: 'dangs-ahwa', name: 'Dangs (Ahwa)' },
      { slug: 'devbhoomi-dwarka', name: 'Devbhoomi Dwarka' },
      { slug: 'gandhinagar', name: 'Gandhinagar' },
      { slug: 'gir-somnath', name: 'Gir Somnath' },
      { slug: 'jamnagar', name: 'Jamnagar' },
      { slug: 'junagadh', name: 'Junagadh' },
      { slug: 'kachchh', name: 'Kachchh' },
      { slug: 'kheda-nadiad', name: 'Kheda (Nadiad)' },
      { slug: 'mahisagar', name: 'Mahisagar' },
      { slug: 'mehsana', name: 'Mehsana' },
      { slug: 'morbi', name: 'Morbi' },
      { slug: 'narmada-rajpipla', name: 'Narmada (Rajpipla)' },
      { slug: 'navsari', name: 'Navsari' },
      { slug: 'panchmahal-godhra', name: 'Panchmahal (Godhra)' },
      { slug: 'patan', name: 'Patan' },
      { slug: 'porbandar', name: 'Porbandar' },
      { slug: 'rajkot', name: 'Rajkot' },
      { slug: 'sabarkantha-himmatnagar', name: 'Sabarkantha (Himmatnagar)' },
      { slug: 'surat', name: 'Surat' },
      { slug: 'surendranagar', name: 'Surendranagar' },
      { slug: 'tapi-vyara', name: 'Tapi (Vyara)' },
      { slug: 'vadodara', name: 'Vadodara' },
      { slug: 'valsad', name: 'Valsad' },
    ],
  },
  {
    slug: 'haryana',
    name: 'Haryana',
    isUT: false,
    districts: [
      { slug: 'ambala', name: 'Ambala' },
      { slug: 'bhiwani', name: 'Bhiwani' },
      { slug: 'charkhi-dadri', name: 'Charkhi Dadri' },
      { slug: 'faridabad', name: 'Faridabad' },
      { slug: 'fatehabad', name: 'Fatehabad' },
      { slug: 'gurgaon', name: 'Gurgaon' },
      { slug: 'hisar', name: 'Hisar' },
      { slug: 'jhajjar', name: 'Jhajjar' },
      { slug: 'jind', name: 'Jind' },
      { slug: 'kaithal', name: 'Kaithal' },
      { slug: 'karnal', name: 'Karnal' },
      { slug: 'kurukshetra', name: 'Kurukshetra' },
      { slug: 'mahendragarh', name: 'Mahendragarh' },
      { slug: 'mewat', name: 'Mewat' },
      { slug: 'palwal', name: 'Palwal' },
      { slug: 'panchkula', name: 'Panchkula' },
      { slug: 'panipat', name: 'Panipat' },
      { slug: 'rewari', name: 'Rewari' },
      { slug: 'rohtak', name: 'Rohtak' },
      { slug: 'sirsa', name: 'Sirsa' },
      { slug: 'sonipat', name: 'Sonipat' },
      { slug: 'yamunanagar', name: 'Yamunanagar' },
    ],
  },
  {
    slug: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    isUT: false,
    districts: [
      { slug: 'bilaspur', name: 'Bilaspur' },
      { slug: 'chamba', name: 'Chamba' },
      { slug: 'hamirpur', name: 'Hamirpur' },
      { slug: 'kangra', name: 'Kangra' },
      { slug: 'kinnaur', name: 'Kinnaur' },
      { slug: 'kullu', name: 'Kullu' },
      { slug: 'lahaul-amp-spiti', name: 'Lahaul &amp; Spiti' },
      { slug: 'mandi', name: 'Mandi' },
      { slug: 'shimla', name: 'Shimla' },
      { slug: 'sirmaur-sirmour', name: 'Sirmaur (Sirmour)' },
      { slug: 'solan', name: 'Solan' },
      { slug: 'una', name: 'Una' },
    ],
  },
  {
    slug: 'jammu-and-kashmir',
    name: 'Jammu and Kashmir',
    isUT: false,
    districts: [
      { slug: 'anantnag', name: 'Anantnag' },
      { slug: 'bandipore', name: 'Bandipore' },
      { slug: 'baramulla', name: 'Baramulla' },
      { slug: 'budgam', name: 'Budgam' },
      { slug: 'doda', name: 'Doda' },
      { slug: 'ganderbal', name: 'Ganderbal' },
      { slug: 'jammu', name: 'Jammu' },
      { slug: 'kargil', name: 'Kargil' },
      { slug: 'kathua', name: 'Kathua' },
      { slug: 'kishtwar', name: 'Kishtwar' },
      { slug: 'kulgam', name: 'Kulgam' },
      { slug: 'kupwara', name: 'Kupwara' },
      { slug: 'leh', name: 'Leh' },
      { slug: 'poonch', name: 'Poonch' },
      { slug: 'pulwama', name: 'Pulwama' },
      { slug: 'rajouri', name: 'Rajouri' },
      { slug: 'ramban', name: 'Ramban' },
      { slug: 'reasi', name: 'Reasi' },
      { slug: 'samba', name: 'Samba' },
      { slug: 'shopian', name: 'Shopian' },
      { slug: 'srinagar', name: 'Srinagar' },
      { slug: 'udhampur', name: 'Udhampur' },
    ],
  },
  {
    slug: 'jharkhand',
    name: 'Jharkhand',
    isUT: false,
    districts: [
      { slug: 'bokaro', name: 'Bokaro' },
      { slug: 'chatra', name: 'Chatra' },
      { slug: 'deoghar', name: 'Deoghar' },
      { slug: 'dhanbad', name: 'Dhanbad' },
      { slug: 'dumka', name: 'Dumka' },
      { slug: 'east-singhbhum', name: 'East Singhbhum' },
      { slug: 'garhwa', name: 'Garhwa' },
      { slug: 'giridih', name: 'Giridih' },
      { slug: 'godda', name: 'Godda' },
      { slug: 'gumla', name: 'Gumla' },
      { slug: 'hazaribag', name: 'Hazaribag' },
      { slug: 'jamtara', name: 'Jamtara' },
      { slug: 'khunti', name: 'Khunti' },
      { slug: 'koderma', name: 'Koderma' },
      { slug: 'latehar', name: 'Latehar' },
      { slug: 'lohardaga', name: 'Lohardaga' },
      { slug: 'pakur', name: 'Pakur' },
      { slug: 'palamu', name: 'Palamu' },
      { slug: 'ramgarh', name: 'Ramgarh' },
      { slug: 'ranchi', name: 'Ranchi' },
      { slug: 'sahibganj', name: 'Sahibganj' },
      { slug: 'seraikela-kharsawan', name: 'Seraikela-Kharsawan' },
      { slug: 'simdega', name: 'Simdega' },
      { slug: 'west-singhbhum', name: 'West Singhbhum' },
    ],
  },
  {
    slug: 'karnataka',
    name: 'Karnataka',
    isUT: false,
    districts: [
      { slug: 'bagalkot', name: 'Bagalkot' },
      { slug: 'ballari-bellary', name: 'Ballari (Bellary)' },
      { slug: 'belagavi-belgaum', name: 'Belagavi (Belgaum)' },
      { slug: 'bengaluru-bangalore-rural', name: 'Bengaluru (Bangalore) Rural' },
      { slug: 'bengaluru-bangalore-urban', name: 'Bengaluru (Bangalore) Urban' },
      { slug: 'bidar', name: 'Bidar' },
      { slug: 'chamarajanagar', name: 'Chamarajanagar' },
      { slug: 'chikballapur', name: 'Chikballapur' },
      { slug: 'chikkamagaluru-chikmagalur', name: 'Chikkamagaluru (Chikmagalur)' },
      { slug: 'chitradurga', name: 'Chitradurga' },
      { slug: 'dakshina-kannada', name: 'Dakshina Kannada' },
      { slug: 'davangere', name: 'Davangere' },
      { slug: 'dharwad', name: 'Dharwad' },
      { slug: 'gadag', name: 'Gadag' },
      { slug: 'hassan', name: 'Hassan' },
      { slug: 'haveri', name: 'Haveri' },
      { slug: 'kalaburagi-gulbarga', name: 'Kalaburagi (Gulbarga)' },
      { slug: 'kodagu', name: 'Kodagu' },
      { slug: 'kolar', name: 'Kolar' },
      { slug: 'koppal', name: 'Koppal' },
      { slug: 'mandya', name: 'Mandya' },
      { slug: 'mysuru-mysore', name: 'Mysuru (Mysore)' },
      { slug: 'raichur', name: 'Raichur' },
      { slug: 'ramanagara', name: 'Ramanagara' },
      { slug: 'shivamogga-shimoga', name: 'Shivamogga (Shimoga)' },
      { slug: 'tumakuru-tumkur', name: 'Tumakuru (Tumkur)' },
      { slug: 'udupi', name: 'Udupi' },
      { slug: 'uttara-kannada-karwar', name: 'Uttara Kannada (Karwar)' },
      { slug: 'vijayapura-bijapur', name: 'Vijayapura (Bijapur)' },
      { slug: 'yadgir', name: 'Yadgir' },
    ],
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    isUT: false,
    districts: [
      { slug: 'alappuzha', name: 'Alappuzha' },
      { slug: 'ernakulam', name: 'Ernakulam' },
      { slug: 'idukki', name: 'Idukki' },
      { slug: 'kannur', name: 'Kannur' },
      { slug: 'kasaragod', name: 'Kasaragod' },
      { slug: 'kollam', name: 'Kollam' },
      { slug: 'kottayam', name: 'Kottayam' },
      { slug: 'kozhikode', name: 'Kozhikode' },
      { slug: 'malappuram', name: 'Malappuram' },
      { slug: 'palakkad', name: 'Palakkad' },
      { slug: 'pathanamthitta', name: 'Pathanamthitta' },
      { slug: 'thiruvananthapuram', name: 'Thiruvananthapuram' },
      { slug: 'thrissur', name: 'Thrissur' },
      { slug: 'wayanad', name: 'Wayanad' },
    ],
  },
  {
    slug: 'lakshadweep',
    name: 'Lakshadweep',
    isUT: true,
    districts: [
      { slug: 'agatti', name: 'Agatti' },
      { slug: 'amini', name: 'Amini' },
      { slug: 'androth', name: 'Androth' },
      { slug: 'bithra', name: 'Bithra' },
      { slug: 'chethlath', name: 'Chethlath' },
      { slug: 'kadmath', name: 'Kadmath' },
      { slug: 'kalpeni', name: 'Kalpeni' },
      { slug: 'kavaratti', name: 'Kavaratti' },
      { slug: 'kilthan', name: 'Kilthan' },
      { slug: 'minicoy', name: 'Minicoy' },
    ],
  },
  {
    slug: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    isUT: false,
    districts: [
      { slug: 'agar-malwa', name: 'Agar Malwa' },
      { slug: 'alirajpur', name: 'Alirajpur' },
      { slug: 'anuppur', name: 'Anuppur' },
      { slug: 'ashoknagar', name: 'Ashoknagar' },
      { slug: 'balaghat', name: 'Balaghat' },
      { slug: 'barwani', name: 'Barwani' },
      { slug: 'betul', name: 'Betul' },
      { slug: 'bhind', name: 'Bhind' },
      { slug: 'bhopal', name: 'Bhopal' },
      { slug: 'burhanpur', name: 'Burhanpur' },
      { slug: 'chhatarpur', name: 'Chhatarpur' },
      { slug: 'chhindwara', name: 'Chhindwara' },
      { slug: 'damoh', name: 'Damoh' },
      { slug: 'datia', name: 'Datia' },
      { slug: 'dewas', name: 'Dewas' },
      { slug: 'dhar', name: 'Dhar' },
      { slug: 'dindori', name: 'Dindori' },
      { slug: 'guna', name: 'Guna' },
      { slug: 'gwalior', name: 'Gwalior' },
      { slug: 'harda', name: 'Harda' },
      { slug: 'hoshangabad', name: 'Hoshangabad' },
      { slug: 'indore', name: 'Indore' },
      { slug: 'jabalpur', name: 'Jabalpur' },
      { slug: 'jhabua', name: 'Jhabua' },
      { slug: 'katni', name: 'Katni' },
      { slug: 'khandwa', name: 'Khandwa' },
      { slug: 'khargone', name: 'Khargone' },
      { slug: 'mandla', name: 'Mandla' },
      { slug: 'mandsaur', name: 'Mandsaur' },
      { slug: 'morena', name: 'Morena' },
      { slug: 'narsinghpur', name: 'Narsinghpur' },
      { slug: 'neemuch', name: 'Neemuch' },
      { slug: 'panna', name: 'Panna' },
      { slug: 'raisen', name: 'Raisen' },
      { slug: 'rajgarh', name: 'Rajgarh' },
      { slug: 'ratlam', name: 'Ratlam' },
      { slug: 'rewa', name: 'Rewa' },
      { slug: 'sagar', name: 'Sagar' },
      { slug: 'satna', name: 'Satna' },
      { slug: 'sehore', name: 'Sehore' },
      { slug: 'seoni', name: 'Seoni' },
      { slug: 'shahdol', name: 'Shahdol' },
      { slug: 'shajapur', name: 'Shajapur' },
      { slug: 'sheopur', name: 'Sheopur' },
      { slug: 'shivpuri', name: 'Shivpuri' },
      { slug: 'sidhi', name: 'Sidhi' },
      { slug: 'singrauli', name: 'Singrauli' },
      { slug: 'tikamgarh', name: 'Tikamgarh' },
      { slug: 'ujjain', name: 'Ujjain' },
      { slug: 'umaria', name: 'Umaria' },
      { slug: 'vidisha', name: 'Vidisha' },
    ],
  },
  {
    slug: 'maharashtra',
    name: 'Maharashtra',
    isUT: false,
    districts: [
      { slug: 'ahmednagar', name: 'Ahmednagar' },
      { slug: 'akola', name: 'Akola' },
      { slug: 'amravati', name: 'Amravati' },
      { slug: 'aurangabad', name: 'Aurangabad' },
      { slug: 'beed', name: 'Beed' },
      { slug: 'bhandara', name: 'Bhandara' },
      { slug: 'buldhana', name: 'Buldhana' },
      { slug: 'chandrapur', name: 'Chandrapur' },
      { slug: 'dhule', name: 'Dhule' },
      { slug: 'gadchiroli', name: 'Gadchiroli' },
      { slug: 'gondia', name: 'Gondia' },
      { slug: 'hingoli', name: 'Hingoli' },
      { slug: 'jalgaon', name: 'Jalgaon' },
      { slug: 'jalna', name: 'Jalna' },
      { slug: 'kolhapur', name: 'Kolhapur' },
      { slug: 'latur', name: 'Latur' },
      { slug: 'mumbai-city', name: 'Mumbai City' },
      { slug: 'mumbai-suburban', name: 'Mumbai Suburban' },
      { slug: 'nagpur', name: 'Nagpur' },
      { slug: 'nanded', name: 'Nanded' },
      { slug: 'nandurbar', name: 'Nandurbar' },
      { slug: 'nashik', name: 'Nashik' },
      { slug: 'osmanabad', name: 'Osmanabad' },
      { slug: 'palghar', name: 'Palghar' },
      { slug: 'parbhani', name: 'Parbhani' },
      { slug: 'pune', name: 'Pune' },
      { slug: 'raigad', name: 'Raigad' },
      { slug: 'ratnagiri', name: 'Ratnagiri' },
      { slug: 'sangli', name: 'Sangli' },
      { slug: 'satara', name: 'Satara' },
      { slug: 'sindhudurg', name: 'Sindhudurg' },
      { slug: 'solapur', name: 'Solapur' },
      { slug: 'thane', name: 'Thane' },
      { slug: 'wardha', name: 'Wardha' },
      { slug: 'washim', name: 'Washim' },
      { slug: 'yavatmal', name: 'Yavatmal' },
    ],
  },
  {
    slug: 'manipur',
    name: 'Manipur',
    isUT: false,
    districts: [
      { slug: 'bishnupur', name: 'Bishnupur' },
      { slug: 'chandel', name: 'Chandel' },
      { slug: 'churachandpur', name: 'Churachandpur' },
      { slug: 'imphal-east', name: 'Imphal East' },
      { slug: 'imphal-west', name: 'Imphal West' },
      { slug: 'jiribam', name: 'Jiribam' },
      { slug: 'kakching', name: 'Kakching' },
      { slug: 'kamjong', name: 'Kamjong' },
      { slug: 'kangpokpi', name: 'Kangpokpi' },
      { slug: 'noney', name: 'Noney' },
      { slug: 'pherzawl', name: 'Pherzawl' },
      { slug: 'senapati', name: 'Senapati' },
      { slug: 'tamenglong', name: 'Tamenglong' },
      { slug: 'tengnoupal', name: 'Tengnoupal' },
      { slug: 'thoubal', name: 'Thoubal' },
      { slug: 'ukhrul', name: 'Ukhrul' },
    ],
  },
  {
    slug: 'meghalaya',
    name: 'Meghalaya',
    isUT: false,
    districts: [
      { slug: 'east-garo-hills', name: 'East Garo Hills' },
      { slug: 'east-jaintia-hills', name: 'East Jaintia Hills' },
      { slug: 'east-khasi-hills', name: 'East Khasi Hills' },
      { slug: 'north-garo-hills', name: 'North Garo Hills' },
      { slug: 'ri-bhoi', name: 'Ri Bhoi' },
      { slug: 'south-garo-hills', name: 'South Garo Hills' },
      { slug: 'south-west-garo-hills', name: 'South West Garo Hills' },
      { slug: 'south-west-khasi-hills', name: 'South West Khasi Hills' },
      { slug: 'west-garo-hills', name: 'West Garo Hills' },
      { slug: 'west-jaintia-hills', name: 'West Jaintia Hills' },
      { slug: 'west-khasi-hills', name: 'West Khasi Hills' },
    ],
  },
  {
    slug: 'mizoram',
    name: 'Mizoram',
    isUT: false,
    districts: [
      { slug: 'aizawl', name: 'Aizawl' },
      { slug: 'champhai', name: 'Champhai' },
      { slug: 'kolasib', name: 'Kolasib' },
      { slug: 'lawngtlai', name: 'Lawngtlai' },
      { slug: 'lunglei', name: 'Lunglei' },
      { slug: 'mamit', name: 'Mamit' },
      { slug: 'saiha', name: 'Saiha' },
      { slug: 'serchhip', name: 'Serchhip' },
    ],
  },
  {
    slug: 'nagaland',
    name: 'Nagaland',
    isUT: false,
    districts: [
      { slug: 'dimapur', name: 'Dimapur' },
      { slug: 'kiphire', name: 'Kiphire' },
      { slug: 'kohima', name: 'Kohima' },
      { slug: 'longleng', name: 'Longleng' },
      { slug: 'mokokchung', name: 'Mokokchung' },
      { slug: 'mon', name: 'Mon' },
      { slug: 'peren', name: 'Peren' },
      { slug: 'phek', name: 'Phek' },
      { slug: 'tuensang', name: 'Tuensang' },
      { slug: 'wokha', name: 'Wokha' },
      { slug: 'zunheboto', name: 'Zunheboto' },
    ],
  },
  {
    slug: 'odisha',
    name: 'Odisha',
    isUT: false,
    districts: [
      { slug: 'angul', name: 'Angul' },
      { slug: 'balangir', name: 'Balangir' },
      { slug: 'balasore', name: 'Balasore' },
      { slug: 'bargarh', name: 'Bargarh' },
      { slug: 'bhadrak', name: 'Bhadrak' },
      { slug: 'boudh', name: 'Boudh' },
      { slug: 'cuttack', name: 'Cuttack' },
      { slug: 'deogarh', name: 'Deogarh' },
      { slug: 'dhenkanal', name: 'Dhenkanal' },
      { slug: 'gajapati', name: 'Gajapati' },
      { slug: 'ganjam', name: 'Ganjam' },
      { slug: 'jagatsinghapur', name: 'Jagatsinghapur' },
      { slug: 'jajpur', name: 'Jajpur' },
      { slug: 'jharsuguda', name: 'Jharsuguda' },
      { slug: 'kalahandi', name: 'Kalahandi' },
      { slug: 'kandhamal', name: 'Kandhamal' },
      { slug: 'kendrapara', name: 'Kendrapara' },
      { slug: 'kendujhar-keonjhar', name: 'Kendujhar (Keonjhar)' },
      { slug: 'khordha', name: 'Khordha' },
      { slug: 'koraput', name: 'Koraput' },
      { slug: 'malkangiri', name: 'Malkangiri' },
      { slug: 'mayurbhanj', name: 'Mayurbhanj' },
      { slug: 'nabarangpur', name: 'Nabarangpur' },
      { slug: 'nayagarh', name: 'Nayagarh' },
      { slug: 'nuapada', name: 'Nuapada' },
      { slug: 'puri', name: 'Puri' },
      { slug: 'rayagada', name: 'Rayagada' },
      { slug: 'sambalpur', name: 'Sambalpur' },
      { slug: 'sonepur', name: 'Sonepur' },
      { slug: 'sundargarh', name: 'Sundargarh' },
    ],
  },
  {
    slug: 'puducherry',
    name: 'Puducherry',
    isUT: true,
    districts: [
      { slug: 'karaikal', name: 'Karaikal' },
      { slug: 'mahe', name: 'Mahe' },
      { slug: 'pondicherry', name: 'Pondicherry' },
      { slug: 'yanam', name: 'Yanam' },
    ],
  },
  {
    slug: 'punjab',
    name: 'Punjab',
    isUT: false,
    districts: [
      { slug: 'amritsar', name: 'Amritsar' },
      { slug: 'barnala', name: 'Barnala' },
      { slug: 'bathinda', name: 'Bathinda' },
      { slug: 'faridkot', name: 'Faridkot' },
      { slug: 'fatehgarh-sahib', name: 'Fatehgarh Sahib' },
      { slug: 'fazilka', name: 'Fazilka' },
      { slug: 'ferozepur', name: 'Ferozepur' },
      { slug: 'gurdaspur', name: 'Gurdaspur' },
      { slug: 'hoshiarpur', name: 'Hoshiarpur' },
      { slug: 'jalandhar', name: 'Jalandhar' },
      { slug: 'kapurthala', name: 'Kapurthala' },
      { slug: 'ludhiana', name: 'Ludhiana' },
      { slug: 'mansa', name: 'Mansa' },
      { slug: 'moga', name: 'Moga' },
      { slug: 'muktsar', name: 'Muktsar' },
      {
        slug: 'nawanshahr-shahid-bhagat-singh-nagar',
        name: 'Nawanshahr (Shahid Bhagat Singh Nagar)',
      },
      { slug: 'pathankot', name: 'Pathankot' },
      { slug: 'patiala', name: 'Patiala' },
      { slug: 'rupnagar', name: 'Rupnagar' },
      { slug: 'sahibzada-ajit-singh-nagar-mohali', name: 'Sahibzada Ajit Singh Nagar (Mohali)' },
      { slug: 'sangrur', name: 'Sangrur' },
      { slug: 'tarn-taran', name: 'Tarn Taran' },
    ],
  },
  {
    slug: 'rajasthan',
    name: 'Rajasthan',
    isUT: false,
    districts: [
      { slug: 'ajmer', name: 'Ajmer' },
      { slug: 'alwar', name: 'Alwar' },
      { slug: 'banswara', name: 'Banswara' },
      { slug: 'baran', name: 'Baran' },
      { slug: 'barmer', name: 'Barmer' },
      { slug: 'bharatpur', name: 'Bharatpur' },
      { slug: 'bhilwara', name: 'Bhilwara' },
      { slug: 'bikaner', name: 'Bikaner' },
      { slug: 'bundi', name: 'Bundi' },
      { slug: 'chittorgarh', name: 'Chittorgarh' },
      { slug: 'churu', name: 'Churu' },
      { slug: 'dausa', name: 'Dausa' },
      { slug: 'dholpur', name: 'Dholpur' },
      { slug: 'dungarpur', name: 'Dungarpur' },
      { slug: 'hanumangarh', name: 'Hanumangarh' },
      { slug: 'jaipur', name: 'Jaipur' },
      { slug: 'jaisalmer', name: 'Jaisalmer' },
      { slug: 'jalore', name: 'Jalore' },
      { slug: 'jhalawar', name: 'Jhalawar' },
      { slug: 'jhunjhunu', name: 'Jhunjhunu' },
      { slug: 'jodhpur', name: 'Jodhpur' },
      { slug: 'karauli', name: 'Karauli' },
      { slug: 'kota', name: 'Kota' },
      { slug: 'nagaur', name: 'Nagaur' },
      { slug: 'pali', name: 'Pali' },
      { slug: 'pratapgarh', name: 'Pratapgarh' },
      { slug: 'rajsamand', name: 'Rajsamand' },
      { slug: 'sawai-madhopur', name: 'Sawai Madhopur' },
      { slug: 'sikar', name: 'Sikar' },
      { slug: 'sirohi', name: 'Sirohi' },
      { slug: 'sri-ganganagar', name: 'Sri Ganganagar' },
      { slug: 'tonk', name: 'Tonk' },
      { slug: 'udaipur', name: 'Udaipur' },
    ],
  },
  {
    slug: 'sikkim',
    name: 'Sikkim',
    isUT: false,
    districts: [
      { slug: 'east-sikkim', name: 'East Sikkim' },
      { slug: 'north-sikkim', name: 'North Sikkim' },
      { slug: 'south-sikkim', name: 'South Sikkim' },
      { slug: 'west-sikkim', name: 'West Sikkim' },
    ],
  },
  {
    slug: 'tamil-nadu',
    name: 'Tamil Nadu',
    isUT: false,
    districts: [
      { slug: 'ariyalur', name: 'Ariyalur' },
      { slug: 'chennai', name: 'Chennai' },
      { slug: 'coimbatore', name: 'Coimbatore' },
      { slug: 'cuddalore', name: 'Cuddalore' },
      { slug: 'dharmapuri', name: 'Dharmapuri' },
      { slug: 'dindigul', name: 'Dindigul' },
      { slug: 'erode', name: 'Erode' },
      { slug: 'kanchipuram', name: 'Kanchipuram' },
      { slug: 'kanyakumari', name: 'Kanyakumari' },
      { slug: 'karur', name: 'Karur' },
      { slug: 'krishnagiri', name: 'Krishnagiri' },
      { slug: 'madurai', name: 'Madurai' },
      { slug: 'nagapattinam', name: 'Nagapattinam' },
      { slug: 'namakkal', name: 'Namakkal' },
      { slug: 'nilgiris', name: 'Nilgiris' },
      { slug: 'perambalur', name: 'Perambalur' },
      { slug: 'pudukkottai', name: 'Pudukkottai' },
      { slug: 'ramanathapuram', name: 'Ramanathapuram' },
      { slug: 'salem', name: 'Salem' },
      { slug: 'sivaganga', name: 'Sivaganga' },
      { slug: 'thanjavur', name: 'Thanjavur' },
      { slug: 'theni', name: 'Theni' },
      { slug: 'thoothukudi-tuticorin', name: 'Thoothukudi (Tuticorin)' },
      { slug: 'tiruchirappalli', name: 'Tiruchirappalli' },
      { slug: 'tirunelveli', name: 'Tirunelveli' },
      { slug: 'tiruppur', name: 'Tiruppur' },
      { slug: 'tiruvallur', name: 'Tiruvallur' },
      { slug: 'tiruvannamalai', name: 'Tiruvannamalai' },
      { slug: 'tiruvarur', name: 'Tiruvarur' },
      { slug: 'vellore', name: 'Vellore' },
      { slug: 'viluppuram', name: 'Viluppuram' },
      { slug: 'virudhunagar', name: 'Virudhunagar' },
    ],
  },
  {
    slug: 'telangana',
    name: 'Telangana',
    isUT: false,
    districts: [
      { slug: 'adilabad', name: 'Adilabad' },
      { slug: 'bhadradri-kothagudem', name: 'Bhadradri Kothagudem' },
      { slug: 'hyderabad', name: 'Hyderabad' },
      { slug: 'jagtial', name: 'Jagtial' },
      { slug: 'jangaon', name: 'Jangaon' },
      { slug: 'jayashankar-bhoopalpally', name: 'Jayashankar Bhoopalpally' },
      { slug: 'jogulamba-gadwal', name: 'Jogulamba Gadwal' },
      { slug: 'kamareddy', name: 'Kamareddy' },
      { slug: 'karimnagar', name: 'Karimnagar' },
      { slug: 'khammam', name: 'Khammam' },
      { slug: 'komaram-bheem-asifabad', name: 'Komaram Bheem Asifabad' },
      { slug: 'mahabubabad', name: 'Mahabubabad' },
      { slug: 'mahabubnagar', name: 'Mahabubnagar' },
      { slug: 'mancherial', name: 'Mancherial' },
      { slug: 'medak', name: 'Medak' },
      { slug: 'medchal', name: 'Medchal' },
      { slug: 'nagarkurnool', name: 'Nagarkurnool' },
      { slug: 'nalgonda', name: 'Nalgonda' },
      { slug: 'nirmal', name: 'Nirmal' },
      { slug: 'nizamabad', name: 'Nizamabad' },
      { slug: 'peddapalli', name: 'Peddapalli' },
      { slug: 'rajanna-sircilla', name: 'Rajanna Sircilla' },
      { slug: 'rangareddy', name: 'Rangareddy' },
      { slug: 'sangareddy', name: 'Sangareddy' },
      { slug: 'siddipet', name: 'Siddipet' },
      { slug: 'suryapet', name: 'Suryapet' },
      { slug: 'vikarabad', name: 'Vikarabad' },
      { slug: 'wanaparthy', name: 'Wanaparthy' },
      { slug: 'warangal-rural', name: 'Warangal (Rural)' },
      { slug: 'warangal-urban', name: 'Warangal (Urban)' },
      { slug: 'yadadri-bhuvanagiri', name: 'Yadadri Bhuvanagiri' },
    ],
  },
  {
    slug: 'tripura',
    name: 'Tripura',
    isUT: false,
    districts: [
      { slug: 'dhalai', name: 'Dhalai' },
      { slug: 'gomati', name: 'Gomati' },
      { slug: 'khowai', name: 'Khowai' },
      { slug: 'north-tripura', name: 'North Tripura' },
      { slug: 'sepahijala', name: 'Sepahijala' },
      { slug: 'south-tripura', name: 'South Tripura' },
      { slug: 'unakoti', name: 'Unakoti' },
      { slug: 'west-tripura', name: 'West Tripura' },
    ],
  },
  {
    slug: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    isUT: false,
    districts: [
      { slug: 'agra', name: 'Agra' },
      { slug: 'aligarh', name: 'Aligarh' },
      { slug: 'allahabad', name: 'Allahabad' },
      { slug: 'ambedkar-nagar', name: 'Ambedkar Nagar' },
      {
        slug: 'amethi-chatrapati-sahuji-mahraj-nagar',
        name: 'Amethi (Chatrapati Sahuji Mahraj Nagar)',
      },
      { slug: 'amroha-j-p-nagar', name: 'Amroha (J.P. Nagar)' },
      { slug: 'auraiya', name: 'Auraiya' },
      { slug: 'azamgarh', name: 'Azamgarh' },
      { slug: 'baghpat', name: 'Baghpat' },
      { slug: 'bahraich', name: 'Bahraich' },
      { slug: 'ballia', name: 'Ballia' },
      { slug: 'balrampur', name: 'Balrampur' },
      { slug: 'banda', name: 'Banda' },
      { slug: 'barabanki', name: 'Barabanki' },
      { slug: 'bareilly', name: 'Bareilly' },
      { slug: 'basti', name: 'Basti' },
      { slug: 'bhadohi', name: 'Bhadohi' },
      { slug: 'bijnor', name: 'Bijnor' },
      { slug: 'budaun', name: 'Budaun' },
      { slug: 'bulandshahr', name: 'Bulandshahr' },
      { slug: 'chandauli', name: 'Chandauli' },
      { slug: 'chitrakoot', name: 'Chitrakoot' },
      { slug: 'deoria', name: 'Deoria' },
      { slug: 'etah', name: 'Etah' },
      { slug: 'etawah', name: 'Etawah' },
      { slug: 'faizabad', name: 'Faizabad' },
      { slug: 'farrukhabad', name: 'Farrukhabad' },
      { slug: 'fatehpur', name: 'Fatehpur' },
      { slug: 'firozabad', name: 'Firozabad' },
      { slug: 'gautam-buddha-nagar', name: 'Gautam Buddha Nagar' },
      { slug: 'ghaziabad', name: 'Ghaziabad' },
      { slug: 'ghazipur', name: 'Ghazipur' },
      { slug: 'gonda', name: 'Gonda' },
      { slug: 'gorakhpur', name: 'Gorakhpur' },
      { slug: 'hamirpur', name: 'Hamirpur' },
      { slug: 'hapur-panchsheel-nagar', name: 'Hapur (Panchsheel Nagar)' },
      { slug: 'hardoi', name: 'Hardoi' },
      { slug: 'hathras', name: 'Hathras' },
      { slug: 'jalaun', name: 'Jalaun' },
      { slug: 'jaunpur', name: 'Jaunpur' },
      { slug: 'jhansi', name: 'Jhansi' },
      { slug: 'kannauj', name: 'Kannauj' },
      { slug: 'kanpur-dehat', name: 'Kanpur Dehat' },
      { slug: 'kanpur-nagar', name: 'Kanpur Nagar' },
      { slug: 'kanshiram-nagar-kasganj', name: 'Kanshiram Nagar (Kasganj)' },
      { slug: 'kaushambi', name: 'Kaushambi' },
      { slug: 'kushinagar-padrauna', name: 'Kushinagar (Padrauna)' },
      { slug: 'lakhimpur-kheri', name: 'Lakhimpur - Kheri' },
      { slug: 'lalitpur', name: 'Lalitpur' },
      { slug: 'lucknow', name: 'Lucknow' },
      { slug: 'maharajganj', name: 'Maharajganj' },
      { slug: 'mahoba', name: 'Mahoba' },
      { slug: 'mainpuri', name: 'Mainpuri' },
      { slug: 'mathura', name: 'Mathura' },
      { slug: 'mau', name: 'Mau' },
      { slug: 'meerut', name: 'Meerut' },
      { slug: 'mirzapur', name: 'Mirzapur' },
      { slug: 'moradabad', name: 'Moradabad' },
      { slug: 'muzaffarnagar', name: 'Muzaffarnagar' },
      { slug: 'pilibhit', name: 'Pilibhit' },
      { slug: 'pratapgarh', name: 'Pratapgarh' },
      { slug: 'raebareli', name: 'RaeBareli' },
      { slug: 'rampur', name: 'Rampur' },
      { slug: 'saharanpur', name: 'Saharanpur' },
      { slug: 'sambhal-bhim-nagar', name: 'Sambhal (Bhim Nagar)' },
      { slug: 'sant-kabir-nagar', name: 'Sant Kabir Nagar' },
      { slug: 'shahjahanpur', name: 'Shahjahanpur' },
      { slug: 'shamali-prabuddh-nagar', name: 'Shamali (Prabuddh Nagar)' },
      { slug: 'shravasti', name: 'Shravasti' },
      { slug: 'siddharth-nagar', name: 'Siddharth Nagar' },
      { slug: 'sitapur', name: 'Sitapur' },
      { slug: 'sonbhadra', name: 'Sonbhadra' },
      { slug: 'sultanpur', name: 'Sultanpur' },
      { slug: 'unnao', name: 'Unnao' },
      { slug: 'varanasi', name: 'Varanasi' },
    ],
  },
  {
    slug: 'uttarakhand',
    name: 'Uttarakhand',
    isUT: false,
    districts: [
      { slug: 'almora', name: 'Almora' },
      { slug: 'bageshwar', name: 'Bageshwar' },
      { slug: 'chamoli', name: 'Chamoli' },
      { slug: 'champawat', name: 'Champawat' },
      { slug: 'dehradun', name: 'Dehradun' },
      { slug: 'haridwar', name: 'Haridwar' },
      { slug: 'nainital', name: 'Nainital' },
      { slug: 'pauri-garhwal', name: 'Pauri Garhwal' },
      { slug: 'pithoragarh', name: 'Pithoragarh' },
      { slug: 'rudraprayag', name: 'Rudraprayag' },
      { slug: 'tehri-garhwal', name: 'Tehri Garhwal' },
      { slug: 'udham-singh-nagar', name: 'Udham Singh Nagar' },
      { slug: 'uttarkashi', name: 'Uttarkashi' },
    ],
  },
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    isUT: false,
    districts: [
      { slug: 'alipurduar', name: 'Alipurduar' },
      { slug: 'bankura', name: 'Bankura' },
      { slug: 'birbhum', name: 'Birbhum' },
      { slug: 'burdwan-bardhaman', name: 'Burdwan (Bardhaman)' },
      { slug: 'cooch-behar', name: 'Cooch Behar' },
      { slug: 'dakshin-dinajpur-south-dinajpur', name: 'Dakshin Dinajpur (South Dinajpur)' },
      { slug: 'darjeeling', name: 'Darjeeling' },
      { slug: 'hooghly', name: 'Hooghly' },
      { slug: 'howrah', name: 'Howrah' },
      { slug: 'jalpaiguri', name: 'Jalpaiguri' },
      { slug: 'kalimpong', name: 'Kalimpong' },
      { slug: 'kolkata', name: 'Kolkata' },
      { slug: 'malda', name: 'Malda' },
      { slug: 'murshidabad', name: 'Murshidabad' },
      { slug: 'nadia', name: 'Nadia' },
      { slug: 'north-24-parganas', name: 'North 24 Parganas' },
      { slug: 'paschim-medinipur-west-medinipur', name: 'Paschim Medinipur (West Medinipur)' },
      { slug: 'purba-medinipur-east-medinipur', name: 'Purba Medinipur (East Medinipur)' },
      { slug: 'purulia', name: 'Purulia' },
      { slug: 'south-24-parganas', name: 'South 24 Parganas' },
      { slug: 'uttar-dinajpur-north-dinajpur', name: 'Uttar Dinajpur (North Dinajpur)' },
    ],
  },
];
