/**
 * Shop Floor - add / edit work order modal.
 *
 * What: party name, product type, qty, ₹/unit, chip colour; status appears
 * in edit mode. The order code (WO-001) is generated by the backend counter.
 *
 * Links: saves through work-orders.actions (createWorkOrder /
 * updateWorkOrder - wired by the page).
 *
 * Watch: form state lives in the inner <OrderForm>, which `destroyOnHidden`
 * unmounts on close - every open mounts fresh from props (no reset effects).
 */

'use client';

import { useState } from 'react';
import { Input, InputNumber, Modal } from 'antd';
import { DsButton, DsSelect, DsOption } from '@/components/ui';
import type {
  CreateWorkOrderPayload,
  UpdateWorkOrderPayload,
  WorkOrder,
  WorkOrderStatus,
} from '@/types';

const PALETTE = [
  '#D97706',
  '#0D9488',
  '#DB2777',
  '#7C3AED',
  '#2563EB',
  '#16A34A',
  '#E11D48',
  '#A16207',
];

interface OrderModalProps {
  open: boolean;
  editOrder?: WorkOrder | null;
  saving: boolean;
  onCancel: () => void;
  onSave: (
    payload: CreateWorkOrderPayload & UpdateWorkOrderPayload,
    editId?: string | null,
  ) => void;
}

export function OrderModal({ open, editOrder, saving, onCancel, onSave }: OrderModalProps) {
  return (
    <Modal
      open={open}
      onCancel={onCancel}
      footer={null}
      width={480}
      destroyOnHidden
      // Scroll the form body internally on short viewports rather than the page.
      style={{ top: 24 }}
      styles={{ body: { maxHeight: 'calc(100vh - 140px)', overflowY: 'auto' } }}
      title={editOrder ? `✎ Edit ${editOrder.code}` : '＋ Work Order'}
    >
      <OrderForm editOrder={editOrder} saving={saving} onSave={onSave} />
    </Modal>
  );
}

/** Inner form - mounts fresh on every modal open (state from initializers). */
function OrderForm({
  editOrder,
  saving,
  onSave,
}: {
  editOrder?: WorkOrder | null;
  saving: boolean;
  onSave: (
    payload: CreateWorkOrderPayload & UpdateWorkOrderPayload,
    editId?: string | null,
  ) => void;
}) {
  const [partyName, setPartyName] = useState(editOrder?.partyName ?? '');
  const [productType, setProductType] = useState(editOrder?.productType ?? '');
  const [qty, setQty] = useState(editOrder?.qty ?? 100);
  const [rate, setRate] = useState(editOrder?.ratePerUnit ?? 50);
  const [colorHex, setColorHex] = useState(editOrder?.colorHex ?? PALETTE[0]);
  const [status, setStatus] = useState<WorkOrderStatus>(editOrder?.status ?? 'active');

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
      <div className="sf-modal-label">Party name</div>
      <Input
        value={partyName}
        placeholder="Shivam Creations"
        maxLength={120}
        onChange={(e) => setPartyName(e.target.value)}
      />
      <div className="sf-modal-label">Product / job type</div>
      <Input
        value={productType}
        placeholder="Job-work dupatta, saree panels…"
        maxLength={120}
        onChange={(e) => setProductType(e.target.value)}
      />
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
        <div>
          <div className="sf-modal-label">Qty (pcs)</div>
          <InputNumber
            aria-label="Quantity"
            min={0}
            value={qty}
            onChange={(v) => setQty(v ?? 0)}
            style={{ width: '100%' }}
          />
        </div>
        <div>
          <div className="sf-modal-label">Rate ₹/unit</div>
          <InputNumber
            aria-label="Rate per unit"
            min={0}
            value={rate}
            onChange={(v) => setRate(v ?? 0)}
            style={{ width: '100%' }}
          />
        </div>
      </div>
      <div className="sf-modal-label">Chip colour</div>
      <div className="sf-pickrow">
        {PALETTE.map((c) => (
          <button
            key={c}
            type="button"
            aria-label={`colour ${c}`}
            className="sf-swatch"
            style={{
              background: c,
              outline: colorHex === c ? '2px solid var(--cr-text)' : 'none',
              outlineOffset: 2,
            }}
            onClick={() => setColorHex(c)}
          />
        ))}
      </div>
      {editOrder && (
        <>
          <div className="sf-modal-label">Status</div>
          <DsSelect
            aria-label="Order status"
            value={status}
            onChange={(v) => setStatus(v as WorkOrderStatus)}
          >
            <DsOption value="active">Active</DsOption>
            <DsOption value="completed">Completed</DsOption>
            <DsOption value="archived">Archived</DsOption>
          </DsSelect>
        </>
      )}
      <div style={{ fontSize: 11, color: 'var(--cr-text-3)', marginTop: 6 }}>
        After adding, open the <b>Process</b> tab and press <b>✨ Standard route</b> to lay the full
        flow in one click.
      </div>
      <DsButton
        dsVariant="primary"
        block
        loading={saving}
        disabled={!partyName.trim()}
        style={{ marginTop: 12 }}
        onClick={() =>
          onSave(
            {
              partyName: partyName.trim(),
              productType: productType.trim() || undefined,
              qty: qty || 0,
              ratePerUnit: rate || 0,
              colorHex,
              ...(editOrder ? { status } : {}),
            },
            editOrder?.id ?? null,
          )
        }
      >
        {editOrder ? 'Save changes' : 'Add order'}
      </DsButton>
    </div>
  );
}
